version: '3.7'

services:

  repository-search-elastic-index:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.elasticsearch.name}:${docker.edu_sharing.community.common.elasticsearch.tag}"
    container_name: "repository-search-elastic-index_${COMPOSE_PROJECT_NAME}"
    environment:
      ES_JAVA_OPTS: >-
        -Xms${REPOSITORY_SEARCH_ELASTIC_INDEX_JAVA_XMS:-512m}
        -Xmx${REPOSITORY_SEARCH_ELASTIC_INDEX_JAVA_XMX:-512m}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
      discovery.type: "single-node"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      xpack.security.enabled: "false"
      http.max_content_length: "2147483647b"
    expose:
      - "7199"
      - "9200"
      - "9300"
    volumes:
      - "repository-search-elastic-index-volume:/usr/share/elasticsearch/data"

  repository-search-elastic-tracker:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-tracker:${docker.tag}"
    container_name: "repository-search-elastic-tracker_${COMPOSE_PROJECT_NAME}"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    environment:
      REPOSITORY_SEARCH_ELASTIC_INDEX_HOST: repository-search-elastic-index
      REPOSITORY_SEARCH_ELASTIC_INDEX_PORT: "9200"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
      MALLOC_ARENA_MAX: "${REPOSITORY_SEARCH_ELASTIC_TRACKER_MALLOC_ARENA_MAX:-2}"
    expose:
      - "7199"
    depends_on:
      - repository-search-elastic-index
      - repository-service

  repository-search-elastic-migration:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-tracker:${docker.tag}"
    container_name: "repository-search-elastic-migration_${COMPOSE_PROJECT_NAME}"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
      - --mode=migration-only
    environment:
      REPOSITORY_SEARCH_ELASTIC_INDEX_HOST: repository-search-elastic-index
      REPOSITORY_SEARCH_ELASTIC_INDEX_PORT: "9200"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
      MALLOC_ARENA_MAX: "${REPOSITORY_SEARCH_ELASTIC_TRACKER_MALLOC_ARENA_MAX:-2}"
    expose:
      - "7199"
    depends_on:
      - repository-search-elastic-index
      - repository-service


  repository-service:
    environment:
      REPOSITORY_SEARCH_ELASTIC_INDEX_HOST: repository-search-elastic-index
      REPOSITORY_SEARCH_ELASTIC_INDEX_PORT: "9200"
    depends_on:
      - repository-search-elastic-index

volumes:
  repository-search-elastic-index-volume: