server.address=0.0.0.0
server.port=18080
alfresco.host=localhost
alfresco.port=8080
elastic.port=9200
alfresco.password=admin


transactions.max = 50
tracker.fetch.size.alfresco = 100
tracker.fetchThumbnails = false
threading.threadCount = 16
trackContent = false
statistic.enabled = false