{{- if .Values.global.backup.velero.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-backup
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
data:
  backup-pre.sh: |-
    #!/bin/bash
    set -e
    while ! curl -s --fail "localhost:9200/_cluster/health?wait_for_status=green"; do echo -n "."; sleep 5 ; done
    if [[ $(hostname) == *-0 ]]; then
      curl -s "localhost:9200/_snapshot" | grep -q "backup" || \
        curl -s -X PUT "localhost:9200/_snapshot/backup" -H 'Content-Type: application/json' -d '{
          "type": "fs",
          "settings": {
            "location": "/usr/share/elasticsearch/share"
          }
        }'
      curl -s -X PUT "localhost:9200/_snapshot/backup/snapshot_$(date +%Y%m%d%H%M%S)?wait_for_completion=true" -H 'Content-Type: application/json' -d '{
        "include_global_state": true
      }'
    fi
    rm -f /usr/share/elasticsearch/share/.velero/restored
  backup-post.sh: |-
    #!/bin/bash
    set -e
    while ! curl -s --fail "localhost:9200/_cluster/health?wait_for_status=green"; do echo -n "."; sleep 5 ; done
    if [[ $(hostname) == *-0 ]]; then
      ALL_SNAPSHOTS=$(curl -s "localhost:9200/_snapshot/backup/_all" | grep -o "snapshot_[0-9-]*")
      for SNAPSHOT in $ALL_SNAPSHOTS; do
        if [[ $(echo $SNAPSHOT | sed 's/snapshot_//') < $(date -d "30 days ago" +%Y%m%d%H%M%S) ]]; then
          curl -s -X DELETE "localhost:9200/_snapshot/backup/$SNAPSHOT"
        fi
      done
    fi
  restore-post.sh: |-
    #!/bin/bash
    set -e
    while ! curl -s --fail "localhost:9200/_cluster/health?wait_for_status=green"; do echo -n "."; sleep 5 ; done
    if [[ $(hostname) == *-0 ]]; then
      curl -s "localhost:9200/_snapshot" | grep -q "backup" || \
        curl -s -X PUT "localhost:9200/_snapshot/backup" -H 'Content-Type: application/json' -d '{
          "type": "fs",
          "settings": {
            "location": "/usr/share/elasticsearch/share"
          }
        }'
      LATEST_SNAPSHOT=$(curl -s "localhost:9200/_snapshot/backup/_all" | grep -o "snapshot_[0-9-]*" | sort | tail -n1)
      curl -s -X POST "localhost:9200/_snapshot/backup/$LATEST_SNAPSHOT/_restore?wait_for_completion=true" -H 'Content-Type: application/json' -d '{
        "include_global_state": true
      }'
    fi
    touch /usr/share/elasticsearch/share/.velero/restored
{{- end }}